apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort  # Change the type to NodePort
  ports:
  - port: 80
    targetPort: 80  # Add targetPort to specify the port on the pod
    nodePort: 30000  # Optional: specify the nodePort (use any valid port number)
  selector:
    app: guestbook
    tier: frontend
